package fix

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/Skeyelab/coauthor-cleaner/internal/config"
	"github.com/Skeyelab/coauthor-cleaner/internal/detect"
	"github.com/Skeyelab/coauthor-cleaner/internal/git"
	"github.com/Skeyelab/coauthor-cleaner/internal/scan"
	"github.com/Skeyelab/coauthor-cleaner/internal/testutil"
)

func initCommit(t *testing.T, dir string) {
	t.Helper()
	testutil.Write(t, dir, "README.md", "init\n")
	testutil.Git(t, dir, "add", "README.md")
	testutil.Git(t, dir, "commit", "-m", "init")
}

func TestRun_CleansStaged(t *testing.T) {
	dir := testutil.GitRepo(t)
	g := git.Runner{Dir: dir}
	initCommit(t, dir)
	testutil.Write(t, dir, "a.go", "// Generated with Claude Code\n")
	testutil.Git(t, dir, "add", "a.go")

	r, err := Run(g, scan.Options{Config: config.Default()}, Options{})
	if err != nil {
		t.Fatal(err)
	}
	if r.Applied != 1 {
		t.Fatalf("applied=%d", r.Applied)
	}
	if !strings.Contains(r.Summary, "Cleaned") {
		t.Fatal(r.Summary)
	}
}

func TestRun_CheckOnly(t *testing.T) {
	dir := testutil.GitRepo(t)
	g := git.Runner{Dir: dir}
	initCommit(t, dir)
	testutil.Write(t, dir, "a.go", "// Generated by ChatGPT\n")
	testutil.Git(t, dir, "add", "a.go")

	r, err := Run(g, scan.Options{Config: config.Default()}, Options{CheckOnly: true})
	if err != nil {
		t.Fatal(err)
	}
	if r.Applied != 0 || !strings.Contains(r.Summary, "Dry run") {
		t.Fatal(r.Summary)
	}
}

func TestRun_NoFindings(t *testing.T) {
	dir := testutil.GitRepo(t)
	g := git.Runner{Dir: dir}
	initCommit(t, dir)
	r, err := Run(g, scan.Options{Config: config.Default()}, Options{})
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(r.Summary, "No AI attribution") {
		t.Fatal(r.Summary)
	}
}

func TestRun_SkipsPushedCommitWithoutForce(t *testing.T) {
	dir := testutil.GitRepo(t)
	g := git.Runner{Dir: dir}
	testutil.Write(t, dir, "README.md", "x\n")
	testutil.Git(t, dir, "add", "README.md")
	testutil.Git(t, dir, "commit", "-m", "init\n\nCo-authored-by: Claude <noreply@anthropic.com>")
	testutil.Git(t, dir, "branch", "-M", "main")
	testutil.Git(t, dir, "remote", "add", "origin", dir)
	testutil.Git(t, dir, "push", "-u", "origin", "main")

	r, err := Run(g, scan.Options{Config: config.Default()}, Options{})
	if err != nil {
		t.Fatal(err)
	}
	if r.SkippedCommit == 0 {
		t.Fatal("expected skipped commit markers")
	}
}

func TestCleanCommitMsgFile(t *testing.T) {
	dir := testutil.GitRepo(t)
	path := filepath.Join(dir, "msg")
	os.WriteFile(path, []byte("feat\n\nCo-authored-by: Claude <noreply@anthropic.com>\n"), 0644)

	findings := []detect.Finding{{
		Source: detect.SourceCommitTrailer, Selected: true, LineNumber: 3,
		Match: "Co-authored-by: Claude <noreply@anthropic.com>",
	}}
	if err := CleanCommitMsgFile(path, findings); err != nil {
		t.Fatal(err)
	}
	data, _ := os.ReadFile(path)
	if strings.Contains(string(data), "Claude") {
		t.Fatalf("%s", data)
	}
}

func TestPlanSummary(t *testing.T) {
	s := planSummary(git.RepoState{}, []detect.Finding{
		{Match: "x", Source: detect.SourceStagedDiff},
	}, 1, Options{Push: true, ForcePush: true})
	if !strings.Contains(s, "force-with-lease") || !strings.Contains(s, "skip 1") {
		t.Fatal(s)
	}
}
