package detect

import (
	"strings"
	"testing"
)

func TestScanLines_ClaudeGeneratedWith(t *testing.T) {
	input := "# Generated with Claude Code\nfunc main() {}\n"
	findings := ScanLines(input, SourceStagedDiff, "app.go", DefaultRules())

	if len(findings) != 1 {
		t.Fatalf("expected 1 finding, got %d", len(findings))
	}
	f := findings[0]
	if f.RuleName != "claude-generated-with" {
		t.Errorf("rule = %q, want claude-generated-with", f.RuleName)
	}
	if f.Match != "# Generated with Claude Code" {
		t.Errorf("match = %q", f.Match)
	}
	if f.Replacement != "" {
		t.Errorf("replacement = %q, want empty", f.Replacement)
	}
	if f.Confidence != ConfidenceHigh {
		t.Errorf("confidence = %q, want high", f.Confidence)
	}
}

func TestScanLines_ChatGPTGenerated(t *testing.T) {
	input := "// Generated by ChatGPT\n"
	findings := ScanLines(input, SourceStagedDiff, "main.go", DefaultRules())

	if len(findings) != 1 {
		t.Fatalf("expected 1 finding, got %d", len(findings))
	}
	if findings[0].RuleName != "chatgpt-generated" {
		t.Errorf("rule = %q", findings[0].RuleName)
	}
}

func TestScanLines_AICoauthorTrailer(t *testing.T) {
	input := "fix: update handler\n\nCo-authored-by: Claude <noreply@anthropic.com>\n"
	findings := ScanLines(input, SourceCommitMessage, "", DefaultRules())

	if len(findings) != 1 {
		t.Fatalf("expected 1 finding, got %d", len(findings))
	}
	f := findings[0]
	if f.Source != SourceCommitTrailer {
		t.Errorf("source = %q, want commit_trailer", f.Source)
	}
	if f.RuleName != "ai-coauthor-trailer" {
		t.Errorf("rule = %q", f.RuleName)
	}
}

func TestScanLines_PreservesHumanCoauthor(t *testing.T) {
	input := "feat: add login\n\nCo-authored-by: Eric Dahl <eric@example.com>\n"
	findings := ScanLines(input, SourceCommitMessage, "", DefaultRules())

	if len(findings) != 0 {
		t.Fatalf("expected 0 findings for human coauthor, got %d: %+v", len(findings), findings)
	}
}

func TestScanLines_CursorGenerated(t *testing.T) {
	input := "Generated with Cursor\n"
	findings := ScanLines(input, SourceStagedDiff, "file.ts", DefaultRules())

	if len(findings) != 1 {
		t.Fatalf("expected 1 finding, got %d", len(findings))
	}
	if findings[0].RuleName != "cursor-generated" {
		t.Errorf("rule = %q", findings[0].RuleName)
	}
}

func TestScanLines_CopilotGenerated(t *testing.T) {
	input := "// Generated by GitHub Copilot\n"
	findings := ScanLines(input, SourceStagedDiff, "file.py", DefaultRules())

	if len(findings) != 1 {
		t.Fatalf("expected 1 finding, got %d", len(findings))
	}
}

func TestScanLines_MultipleFindings(t *testing.T) {
	input := strings.Join([]string{
		"# Generated with Claude Code",
		"// Generated by ChatGPT",
		"real code here",
	}, "\n")
	findings := ScanLines(input, SourceStagedDiff, "app.rb", DefaultRules())

	if len(findings) != 2 {
		t.Fatalf("expected 2 findings, got %d", len(findings))
	}
}

func TestCleanText_RemovesSelectedLines(t *testing.T) {
	input := "# Generated with Claude Code\nfunc main() {}\n"
	findings := ScanLines(input, SourceStagedDiff, "app.go", DefaultRules())
	for i := range findings {
		findings[i].Selected = true
	}

	cleaned := CleanText(input, findings)
	want := "func main() {}\n"
	if cleaned != want {
		t.Errorf("cleaned = %q, want %q", cleaned, want)
	}
}

func TestCleanText_PreservesUnselected(t *testing.T) {
	input := "# Generated with Claude Code\nfunc main() {}\n"
	findings := ScanLines(input, SourceStagedDiff, "app.go", DefaultRules())
	for i := range findings {
		findings[i].Selected = false
	}

	cleaned := CleanText(input, findings)
	if cleaned != input {
		t.Errorf("unselected should preserve input")
	}
}

func TestScanLines_AllowedTrailerOverride(t *testing.T) {
	input := "Co-authored-by: Claude <noreply@anthropic.com>\n"
	findings := ScanLines(input, SourceCommitMessage, "", DefaultRules(), ScanOpts{
		AllowedTrailers: []string{"Co-authored-by: Claude"},
	})
	if len(findings) != 0 {
		t.Fatalf("expected allowed trailer to be skipped, got %d", len(findings))
	}
}

func TestStrictMode_FewerMatches(t *testing.T) {
	input := "// This code was assisted by AI\n"
	strict := ScanLines(input, SourceStagedDiff, "f.go", StrictRules())
	aggressive := ScanLines(input, SourceStagedDiff, "f.go", AggressiveRules())

	if len(strict) != 0 {
		t.Errorf("strict should not match generic AI text, got %d", len(strict))
	}
	if len(aggressive) < 1 {
		t.Errorf("aggressive should match generic AI text")
	}
}
