package scan

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/Skeyelab/coauthor-cleaner/internal/config"
)

func TestScanPath_File(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "readme.md")
	os.WriteFile(path, []byte("# Generated with Claude Code\n"), 0644)

	findings, err := ScanPath(path, config.Default(), false, false)
	if err != nil {
		t.Fatal(err)
	}
	if len(findings) != 1 {
		t.Fatalf("expected 1 finding, got %d", len(findings))
	}
}

func TestScanPath_Dir(t *testing.T) {
	dir := t.TempDir()
	os.WriteFile(filepath.Join(dir, "a.go"), []byte("// Generated by ChatGPT\n"), 0644)
	os.Mkdir(filepath.Join(dir, "node_modules"), 0755)
	os.WriteFile(filepath.Join(dir, "node_modules", "skip.go"), []byte("// Generated by ChatGPT\n"), 0644)

	findings, err := ScanPath(dir, config.Default(), false, false)
	if err != nil {
		t.Fatal(err)
	}
	if len(findings) != 1 {
		t.Fatalf("expected 1 finding (node_modules skipped), got %d", len(findings))
	}
}
